### ISSUE TITLE
Community Post page is accessible even with no user signed in.

### ISSUE THREAD

**Issue by CERTIFIED2003** [SashenJayathilaka/Reddit-Clone#54]
Just leaving you a heads up that **Submit** page of a **Community** is accessible even if user is not logged in.
![Screenshot for reference](https://user-images.githubusercontent.com/111045472/220154875-c784d19f-9b69-4db6-8ac5-6d8a0d074d08.png)

The **_submit.tsx_** file should be a protected route so that no user can access this page without authenticating.

**Comment by SashenJayathilaka** [comment]
Yes, even if no user is signed in, the user can access the site. But users can't create a post without logging in. Users must log in to their accounts in order to create and submit a post.

**Comment by CERTIFIED2003** [comment]
You can head over to my Community page [Reddit Clone](https://r-clone.vercel.app/r/WeKnewHow). I have corrected this error on my [submit.tsx](https://github.com/CERTIFIED2003/Reddit-Clone/blob/main/src/pages/r/%5BcommunityId%5D/submit.tsx) file. You can have a look.

**Comment by SashenJayathilaka** [comment]
Yeah, I will fix this issue. Thanks for your suggestion.
