### ISSUE TITLE
Hydration failed

### ISSUE THREAD

**Issue by sandwitcherz** [SashenJayathilaka/Reddit-Clone#57]
Hello, i have correctly configured firebase, i use npm 16, 17, 18, 19, but all says the same error:

```
Unhandled Runtime Error

Error: Hydration failed because the initial UI does not match what was rendered on the server.
and
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

have you a solution for this?

Thank you a lot for this project.

Here is the txt whith the errors : https://drop.devweb.ovh/viewSJQQ

**Comment by SashenJayathilaka** [comment]
Could you please tell me the version of your "Next js"? 13 or 12?

**Comment by sandwitcherz** [comment]
you speak about nodejs?
nodejs --version
v12.22.12

**Comment by SashenJayathilaka** [comment]
No, I mean Next Js. Go to your project and go to your `package. json` and find the `next`  version

**Comment by sandwitcherz** [comment]
yes i have modify my post ^^ Next.js v12.2.5

**Comment by SashenJayathilaka** [comment]
### First Method

Hydration error means some UI error is happening only on your local server. but I will give a solution to it. First, you go to your project directory, go to your `src/components` directory, and create a file called `ClientOnly.tsx`.

and this `ClientOnly.tsx` file, edit below like this:

`ClientOnly.tsx`
```tsx
import React, { useEffect, useState } from "react";

type Props = {
  children: React.ReactNode;
};

function ClientOnly({ children }: Props) {
  const [hasMounted, setHasMounted] = useState(false);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  if (!hasMounted) {
    return null;
  }

  return (
    <div>{children}</div>
  );
}

export default ClientOnly;
```

After that, go to your  `src/page` directory and go to your `_app.tsx` file, and it should change below like this:

```tsx
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import { RecoilRoot } from "recoil";

import { theme } from "../chakra/theme";
import Layout from "../components/Layout/Layout";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      <ChakraProvider theme={theme}>
        <ClientOnly>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </ClientOnly>
      </ChakraProvider>
    </RecoilRoot>
  );
}

export default MyApp;

```

<hr />

### Second Method

#### If not, you can do it in a simple way like this:

go to your 'Layout.tsx' file and change it like this 

```tsx
import React, { useEffect, useState } from "react";
import Navbar from "../../Navbar/Navbar";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [hasMounted, setHasMounted] = useState(false);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  if (!hasMounted) {
    return null;
  }

  return (
    <>
      <Navbar />
      <main>{children}</main>
    </>
  );
};

export default Layout;
```


You can do the first method or the second method

**Comment by sandwitcherz** [comment]
Thank you a lot, i am going to try this.

**Comment by sandwitcherz** [comment]
so, the first solution works, if i remove ClientOnly in _app.tsx :)
if i put it, i have ReferenceError: ClientOnly is not defined

But i know i must investigate myself, so, thak you for your time :)

Have a nice day!

**Comment by GTMany** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sddxyangguo, @sunalbert, @licett, @ellonyang, @spiderT, @joaquinchen, @wang0402, @ccreater222, @ThanLoo, @xuling1979, @thecatshidog, @yeahwong, @yepengjun, @yimity, @Richard-HAN-Coding, @zcieng, @tonyprince6, @azoth1991, @niettcat, @Allenkc, @Nikoace, @gasolin, @ZachariahQi, @toadfansboy, @WanderKey, @seelunzi, @PeiQi0, @Jodragon, @wenxinTuring, @veficos, @qbmiller, @lyonnee, @panwenwei, @xiajinchun, @dxdw233, @ggboy0-48, @sleep-go, @RealCoolSnow, @yunfetian, @jhonnymoree, @baizeit, @concave-engineering, @zhenyin1011, @dongguaguaguagua, @calify, @Dkbabyfzz, @msjin, @Coder-DjangoMo, @smiojnw, @xyuu98Minnolas, @afan0918, @fredyj, @kisniuniu, @TrumanDu, @taogezhizun, @KevinJay, @SysuCodeRookie, @The-Feng, @eastrisingchu, @davidhex, @Euraxluo, @123guanxing, @blockwhalex, @jamesbayy, @heyanfeng, @traceurl, @KyleYangSde, @wureny, @Prometheo, @Tomato-Java, @JacobDu, @FaCai8, @wongyeefoo, @giwankim, @Pure-Peace, @tmlaes, @gaozhenyusky, @ajaxbo360, @mmmkkk82, @KunSa1024, @ZhangyuchaoCN, @sun-1997218, @ljybill, @fishonline, @ElijahGodrand, @YongcanZhou, @hmilydorothy, @yaohualongRex, @frikent, @Derek-X-Wang, @LiJiangYin, @Stevefanfan, @Tao-2000, @cppfuns, @syffs, @vnhacker1337, @schrodingercatss, @yuyan-sec, @bk201zlw0x0xy, @knjf, @DevinWeb3, @YTU94, @moonlove7, @JLQmiller, @Wmmeng, @nian8, @Quanhua-Guan, @lesser-P, @elvise7777, @amirk1998, @x7LoveLin, @Hzao, @Howard0401, @HelenHE408, @tyzhang1990, @lxdmgm, @Alice-and-Bob, @KuJyoAi, @bacnd, @lomo5, @jiyeking, @Desgard, @onlypromise, @j1anFen, @yisa2, @goxduck, @DanielWongkkk, @LinKenCong, @afunTW, @bitnan798, @zvv369, @busyDecoding, @yizhilee, @dragon2031, @kingcai2022, @qojo111, @GoldRush520, @manzxiao, @benzhipeng, @eurekawild, @apan0206, @superwomanliuda, @zym4ever2020, @magicube101, @masonsxu, @Loyalsoldier, @nickboot, @akanoodleTickdack, @MondayWoo, @sunyulin6351, @ashishbinu, @thi-investax, @rguo5705, @ZHOUWU001, @xh897, @wmvm0, @0nlydu, @yz-solo, @onchainzugzwang, @FE-Luke, @surgit, @meet-cjli, @lakai, @madao708, @youkicl, @54441384, @faintaste, @bestoko, @Jack-ym, @lushan88a, @yuanyu90221, @yaun369, @miuchan, @Valuebai, @3lang3, @xrmr, @Nandtris, @a00012025, @jeffierw, @qq763253009, @WENCHING6, @guoabyss, @mewcoder, @Meng-xiangkun, @solofomo, @kaixa0, @boycetien, @secreter, @gavfu, @shaopoooo, @mxmal, @rhsor, @sweatFlower, @shawnlu96, @QixinYou, @shubh402, @luckyboy2226huwangtao123, @mustangxu, @Noctsyndrome, @OMP1024, @ntut-xuan, @Luke9086, @little-zhong, @kkjj5566123, @tworuler, @twcctop, @VilaNan, @Liuddw, @Y-Xiang-hub, @yefuchao, @1anyway, @bobyeoh, @Saber2pr, @Iamasoldier6, @w3lc, @0xTac, @greatpie, @lizhiyu-me, @crazywai1221, @ganzhoumengnan, @wsjack22, @MondayWoo, @fei316, @HelloYLee, @JJLau626, @8Marchisio, @cnxzcxy, @Lobok7, @Zjlkk, @cy920820, @krsoy, @Ractive89, @helmvon, @shinnc, @zheng769673192, @SeverusHuang-HLF, @tudouya, @haigendong, @Chancelife, @Mrfranken, @lamengao, @bigEYEleg100, @bluegitter, @CorradoRossi, @tsubasakong, @echobossouyang913, @0xFar777, @kidneyweakx, @0xOutOfGas, @NNNyasuolong, @ANITOCE, @Coldwinds5167, @milo763, @chenbimo, @DishantPal, @JueShanCoder, @wwwjinlong, @wesson-yi, @SpaceSkater, @RENGELETH, @BiYuqi, @MuRKuo, @someone120, @GoMaL, @boximiya, @qililime, @CodeDreamfy, @jack21, @bidman2023001, @Gambler9123, @kaiser-9527, @cjm00n, @netrazor, @Zz0979, @nooooocato, @xfkencon, @island7, @Freshield, @gududefengzhong, @Zenas1023, @Shaker-Chen, @shaozee, @VAIIO31, @codemakerss, @jingkang99, @UCASZ, @kunjsong01, @CarlWang007, @zhangmingqi09, @Yuumi0221, @chuangbo, @DogeEgg, @whycode, @MissCoconut, @Hvnt3rmormoon007, @SuuuuperL, @mookim-eth, @chengaoang, @gofancyever, @qiuzaiqing, @he0x, @tyroyang, @406975648, @liron-li, @bihaiqinkong, @lyricremix, @Acrossstars, @jaan1025, @t0hka1, @oscnet, @mikezhouhan, @wangLi007, @jjmlife, @Tenlercy, @HONGYI-SD, @JiuFang-Java, @Hardcoreyoyo, @Sunnyy20, @ZhiXuanWang, @wodis, @Tencnet777, @daiwenyong, @jackhh66, @StriveMoring, @332439180, @jiaochenglong, @jiangbo9510, @WulaSilver, @Shawnlee101, @BLTC-520, @HeleMK, @Tom001326, @RoyHonChain, @dawndst, @zwq652997, @1665461jyj, @zaunww, @skyhighbirdfly, @viokuma, @Lumend, @2420479972, @77629296, @jucky1, @yfchen18tanghoong, @erRORatao, @houjunchen, @kayaYuan, @workless, @terryops, @BigFatBro, @ben46, @FE-Luke, @lbleo211, @CryptoHugh, @wkmie, @Tiancheng-Xu, @aristotll, @joker9657, @pfsir, @WaterSo0910, @1974410167, @runningwa, @songtianyi, @Dovahkinn, @Cy-zhen, @Love4yzp, @LanyieJ, @starmapz, @Miluer-tcq, @mikaelyoulove, @frank-leeee, @13925891880, @bearomorphism, @zhaxzhax, @grumpyxui, @fkallweb3, @nbb2025, @yilongli, @gaowenzhen, @ws456999, @zywebcn, @asdhasvd, @zhaohao19941221, @SherlockGuoz, @sunhapper, @dars, @zoushanji, @0v3rW4tch, @xiachongbukeyubing333, @zhou16, @HToTH, @sunitey, @quantum-proof42-lab, @foreverxdord, @Feuda, @kaiming294, @JavHou, @Calvintag, @emmmmnm, @pekandhangc, @1055373165, @3200459199, @chenyu1024, @ChenBna, @Marchlie, @DonMitime, @soreatu, @blackmiaool, @coderlauu, @wangzilaogong, @3235773541, @sunui, @yz-solo, @artisticbones, @EronTo, @enriquephlin, @yiruacm, @FF99CC, @jiffies, @YHM404, @mortence, @aewc, @libin2866, @xiaohuangniuu, @antrope, @yuuuuu422, @landa-lab, @suddenly1990, @Andytreee, @yangyulele, @wanghche, @lemengleng, @TenviLi, @conglt-0917, @Gene1994, @hanniballei, @Osub, @luffythink, @eddy8, @pengbo37877, @pinoccc3, @WhiteRiverBayfreemanxzx, @lllleeo, @ericssonxiao, @donaldxdonald, @hymnfish, @hnhhm2000, @gofreeapp, @liyi1123, @jrr997, @willzcc, @unajingjing, @entheowww, @jiesns, @HouqiXie, @qyvlik, @Markli66, @0lh, @xiaoxiaomuyuziguiti, @windmaple, @dongjindong, @vencent2006, @yuankongzhe, @metaforcode, @jojo51778, @z0uki, @sunsimon, @2exd, @happypayne, @miketsui3a, @lili574, @MaybeMonad, @eurekame2000, @hjhsnail, @loktarjugg, @imbafym, @LQ-200826, @zhaomin6666, @AloneAtWar, @victory81, @renyufly, @JayY0ung, @i6u, @maple2012, @MatrixA, @chrisguox, @HeleMK, @jk00000000, @xiatian2643, @mhw1902, @wyj6039
